# Generated by Django 4.0.1 on 2022-01-31 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Country_name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Plant_name')),
                ('plant_type', models.IntegerField(choices=[(1, 'Однолетнее'), (2, 'Многолетнее'), (3, 'Кустовое'), (4, 'Древовидное')], verbose_name='Plant_type')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Plantation_name')),
                ('description', models.TextField(verbose_name='Description')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantation.country', verbose_name='Country')),
                ('plants', models.ManyToManyField(to='Plantation.Plant', verbose_name='Plants')),
            ],
            options={
                'verbose_name': 'Plantation',
                'verbose_name_plural': 'Plantations',
            },
        ),
    ]
